modules-search: [ local ]

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  {{createUsers}}users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  {{hasSystemd}}machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - plymouthcfg
  - luksbootkeyfile
  - dracutlukscfg
  {{createUsers}}users
  {{hasDisplaymanager}}displaymanager 
  - networkcfg
  - hwclock
  {{hasSystemd}}services-systemd 
  - dracut
  - bootloaderspecification
  - grubcfg
  - bootloader
  - packages
  - removeuser
  - umount
- show:
  - finished
branding: {{branding}}
prompt-install: true
dont-chroot: false
