 # Ubuntu 24.04 noble
---
modules-search: [ local ]

instances:
#- id: before_bootloader_mkdirs
#  module: contextualprocess
#  config: before_bootloader_mkdirs_context.conf
#- id: before_bootloader
#  module: contextualprocess
#  config: before_bootloader_context.conf
#- id: logs
#  module: shellprocess
#  config: shellprocess_logs.conf
- id: bug-LP#1829805
  module: shellprocess
  config: shellprocess_bug-LP#1829805.conf
- id: add386arch
  module: shellprocess
  config: shellprocess_add386arch.conf
- id: boot_deploy
  module: shellprocess
  config: shellprocess@boot_deploy.conf
- id: boot_reconfigure
   module: shellprocess
   config: shellprocess@boot_reconfigure.conf
#- id: pkgselect_action
#  module: contextualprocess
#  config: pkgselect_context.conf
#- id: pkgselect_snap_action
#  module: contextualprocess
#  config: pkgselect_snap_context.conf
- id: oemprep
  module: shellprocess
  config: shellprocess_oemprep.conf
- id: fixconkeys_part1
  module: shellprocess
  config: shellprocess_fixconkeys_part1.conf
- id: fixconkeys_part2
  module: shellprocess
  config: shellprocess_fixconkeys_part2.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  # pkgselect
  - partition
  {{createUsers}}users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  {{hasSystemd}}machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  {{createUsers}}users
  {{hasDisplaymanager}}displaymanager
  - networkcfg
  - hwclock
  #- contextualprocess@before_bootloader_mkdirs
  - shellprocess@bug-LP#1829805
  - shellprocess@boot_deploy        # added
  - shellprocess@boot_reconfigure   # added
  - initramfscfg
  - initramfs
  - grubcfg
  #- contextualprocess@before_bootloader
  - bootloader
  # automirror
  - shellprocess@add386arch
  - shellprocess@fixconkeys_part1
  - shellprocess@fixconkeys_part2
  - packages
  - removeuser  
  # contextualprocess@pkgselect_action
  # contextualprocess@pkgselect_snap_action
  # shellprocess@logs
  - cleanup
  - sources-yolk-undo
  - umount
- show:
  - finished

branding: {{branding}}
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
