# Nome del workflow che apparirà nella UI di GitHub
name: 000 - Release all

# Trigger manuale con il pulsante "Run workflow"
on:
  workflow_dispatch:

jobs:
  # L'unico job di questo file è "chiamare" gli altri.
  trigger-all-releases:
    runs-on: ubuntu-latest
    
    # IMPORTANTE: Devi dare al workflow il permesso di avviarne altri.
    # Per motivi di sicurezza, non è un'impostazione predefinita.
    permissions:
      actions: write

    steps:
      - name: Avvio di tutti i workflow di pubblicazione
        # Usiamo la GitHub CLI (gh), che è preinstallata sui runner di GitHub
        env:
          # Il token è necessario per autenticare la CLI e permetterle
          # di eseguire azioni a nome tuo nel repository.
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Inizio a chiamare i singoli workflow sulla versione ${{ inputs.version }}..."

          # Per ogni workflow, eseguiamo il comando 'gh workflow run'
          # specificando il nome del file .yml.
          # '--ref' indica su quale branch/tag eseguire il workflow (in questo caso, quello specificato nell'input).
          gh workflow run 00-publish-debian-deb.yml --ref ${{ github.ref }}
          gh workflow run 01-publish-fedora-rpm.yml --ref ${{ github.ref }}
          gh workflow run 02-publish-opensuse-rpm.yml --ref ${{ github.ref }}
          gh workflow run 03-publish-enterprise-linux.yml --ref ${{ github.ref }}
          gh workflow run 04-publish-archlinux.yml --ref ${{ github.ref }}
          gh workflow run 05-publish-manjaro.yml --ref ${{ github.ref }}
          gh workflow run 06-publish-alpine.yml --ref ${{ github.ref }}
          
          echo "✅ Tutti i workflow sono stati avviati!"
