# Nome del workflow, specifico per Fedora
name: 01. Build and Publish Fedora RPM

# Controllo per evitare conflitti di scrittura
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  BOOTLOADERS_VERSION: v25.9.8

jobs:
  # --- JOB 1: COSTRUISCE IL PACCHETTO PER FEDORA ---
  build-fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:42
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 2. Install Build Dependencies (with jq)
        run: |
          dnf install -y 'dnf-plugins-core' rpm-build git tar gzip curl gnupg2 rpmsign jq
          for package in $(grep '^BuildRequires:' packaging/rpm/penguins-eggs.spec | awk '{print $2}'); do
            dnf install -y "$package"
          done

      - name: 3. Get Package Version from package.json
        id: version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: 4. Update Version in .spec File
        run: |
          echo "Updating .spec file to version ${{ steps.version.outputs.version }}"
          sed -i "s/^\(Version: *\).*/\1${{ steps.version.outputs.version }}/" packaging/rpm/penguins-eggs.spec

      - name: 5. Import GPG Key and Configure RPM
        run: |
          echo "${{ secrets.GPG_SIGNING_KEY }}" | gpg --import --batch
          echo '%_signature gpg' > ~/.rpmmacros
          echo '%_gpg_name ${{ secrets.GPG_KEY_ID }}' >> ~/.rpmmacros

      - name: 6. Prepare RPM Sources
        run: |
          mkdir -p $HOME/rpmbuild/SOURCES
          tar -czf $HOME/rpmbuild/SOURCES/penguins-eggs.tar.gz \
            --transform='s,^\.,penguins-eggs-${{ steps.version.outputs.version }},' \
            --exclude=.git --exclude=.github .
          curl -LO https://github.com/pieroproietti/penguins-bootloaders/releases/download/${{ env.BOOTLOADERS_VERSION }}/bootloaders.tar.gz
          cp bootloaders.tar.gz $HOME/rpmbuild/SOURCES/

      - name: 7. Build and Sign RPM package
        id: build
        run: |
          mkdir -p ~/.gnupg
          echo "pinentry-