name: 04. Build Arch Linux Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  # --- JOB 1: COSTRUISCE IL PACCHETTO PER ARCH LINUX ---
  build-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Prepare Build Environment and Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git pnpm

      - name: 3. Create Build User and Set Permissions
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder "$GITHUB_WORKSPACE"

      - name: 4. Build The Package as Non-Root User
        run: sudo -u builder makepkg -s --noconfirm
        working-directory: ./packaging/arch
      
      - name: 5. Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-package
          path: ./packaging/arch/*.pkg.tar.zst

  # --- JOB 2: PUBBLICA SUL REPOSITORY (DOPO IL BUILD) ---
  publish-repo:
    needs: build-arch
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout existing repo
        uses: actions/checkout@v4
        with:
          repository: pieroproietti/penguins-eggs-repo
          token: ${{ secrets.PUBLISH_TOKEN }}
          path: repo-dir

      - name: 2. Download Arch Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: archlinux-package
          path: repo-dir/arch/

      - name: 3. Update and Sign Arch Linux Repository
        uses: container-actions/run-in-container@v1
        with:
          image: archlinux
          dockerOptions: -v ${{ github.workspace }}/repo-dir:/work
          env:

            GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
            GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
            GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          run: |
            set -e
            cd /work/arch
            
            pacman -Syu --noconfirm
            pacman -S --noconfirm base-devel

            echo "$GPG_SIGNING_KEY" | gpg --import --batch
            mkdir -p ~/.gnupg
            echo "pinentry-mode loopback" > ~/.gnupg/gpg.conf
            echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
            gpg-connect-agent reloadagent /bye
            
            echo "$GPG_PASSPHRASE" | gpg --batch --yes --passphrase-fd 0 -o /dev/null -s /dev/null
            
            repo-add --sign --key "$GPG_KEY_ID" penguins-eggs.db.tar.gz *.pkg.tar.zst

      - name: 4. Deploy to penguins-eggs-repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PUBLISH_TOKEN }}
          external_repository: pieroproietti/penguins-eggs-repo
          publish_branch: main
          publish_dir: ./repo-dir
          keep_files: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: "Update Arch Linux repository"

