# Nome del workflow, specifico per Arch Linux
name: 04. Build and Publish Arch Linux Repository

# Controllo per evitare conflitti di scrittura su gh-pages
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  # --- JOB 1: COSTRUISCE IL PACCHETTO PER ARCH LINUX ---
  build-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Prepare Build Environment and Dependencies
        run: |
          pacman -Syu --noconfirm
          # Aggiungiamo gnupg per la firma
          pacman -S --noconfirm base-devel git pnpm gnupg

      - name: 3. Create Build User and Set Permissions
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder "$GITHUB_WORKSPACE"

      - name: 4. Import GPG Key
        run: |
          # Diamo la chiave GPG all'utente builder
          sudo -u builder gpg --import -
        shell: bash
        stdin: ${{ secrets.GPG_SIGNING_KEY }}

      - name: 5. Build and Sign The Package as Non-Root User
        id: build
        run: |
          # Dobbiamo specificare l'ID della chiave da usare per la firma
          sudo -u builder makepkg -s --sign --key ${{ secrets.GPG_KEY_ID }} --noconfirm
          echo "pkg_path=$(find . -name '*.pkg.tar.zst')" >> $GITHUB_OUTPUT
        working-directory: ./packaging/arch
        
      - name: 6. Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-package-for-repo
          path: ${{ steps.build.outputs.pkg_path }}

  # --- JOB 2: PUBBLICA SUL REPOSITORY (DOPO IL BUILD) ---
  publish-repo:
    needs: build-arch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Eseguiamo anche questo job in un container Arch per avere gli strumenti giusti (`repo-add`)
    container:
      image: archlinux
    steps:
      - name: 1. Install Prerequisite Tools
        run: |
          pacman -Syu --noconfirm
          # 'repo-add' si trova nel pacchetto 'pacman-contrib'
          pacman -S --noconfirm git pacman-contrib gnupg

      - name: 2. Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          
      - name: 3. Create directory structure
        run: mkdir -p arch/x86_64

      - name: 4. Download Arch package artifact
        uses: actions/download-artifact@v4
        with:
          name: archlinux-package-for-repo
          path: ./arch/x86_64

      - name: 5. Update and Sign Arch Repository
        run: |
          cd ./arch/x86_64
          # Il nome del database del repository (es. penguins-eggs.db.tar.gz)
          REPO_NAME="penguins-eggs"
          
          # Aggiungiamo il nuovo pacchetto al database del repository
          # Questo comando crea il file .db.tar.gz se non esiste
          repo-add ${REPO_NAME}.db.tar.gz *.pkg.tar.zst
          
          # Firmiamo il database del repository
          echo "${{ secrets.GPG_SIGNING_KEY }}" | gpg --import --batch
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --passphrase-fd 0 --pinentry-mode loopback --detach-sign --armor -u ${{ secrets.GPG_KEY_ID }} ${REPO_NAME}.db.tar.gz

      - name: 6. Commit and Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # Usiamo un PAT perche' il container Arch non ha un ambiente git pre-configurato
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: .
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
