name: 04. Build Arch Linux Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  # --- JOB 1: COSTRUISCE IL PACCHETTO PER ARCH LINUX ---
  build-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Prepare Build Environment and Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git pnpm

      - name: 3. Create Build User and Set Permissions
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder "$GITHUB_WORKSPACE"

      - name: 4. Build The Package as Non-Root User
        run: sudo -u builder makepkg -s --noconfirm
        working-directory: ./packaging/arch
      
      - name: 5. Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-package
          path: ./packaging/arch/*.pkg.tar.zst

