name: Build Fedora Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-rpm-fedora:
    runs-on: ubuntu-latest
    
    container:
      image: fedora:42

    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4
        # Lasciamo fetch-depth: 0, non fa male
        with:
          fetch-depth: 0

      - name: 2. Install Core Tools
        run: dnf install -y git tar gzip

      - name: 3. Download Bootloaders
        run: curl -LO https://github.com/pieroproietti/penguins-bootloaders/releases/download/v25.9.8/bootloaders.tar.gz

      - name: 4. Install Build Dependencies
        run: |
          dnf install -y rpm-build dnf-plugins-core
          dnf builddep -y ./packaging/rpm/penguins-eggs.spec

      # --- STEP MODIFICATO ---
      - name: 5. Prepare RPM Sources (using tar)
        run: |
          mkdir -p $HOME/rpmbuild/SOURCES
          
          # SOSTITUIAMO 'git archive' CON 'tar'.
          # Questo comando crea un tarball dal contenuto della cartella corrente,
          # escludendo la cartella .git (se mai ci fosse) e .github.
          # Lavora sui file, che sappiamo esserci.
          tar -czf $HOME/rpmbuild/SOURCES/penguins-eggs-25.9.8.tar.gz --exclude=.git --exclude=.github .
          
          cp bootloaders.tar.gz $HOME/rpmbuild/SOURCES/

      - name: 6. Build RPM package
        run: rpmbuild -ba ./packaging/rpm/penguins-eggs.spec

      - name: 7. Upload RPM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fedora-42-rpm
          path: ~/rpmbuild/RPMS/**/*.rpm