name: Build Arch Linux Package (Diagnostic)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-pkg-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Prepare Build Environment
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git pnpm

      - name: 3. Create a non-root user and set permissions
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder "$GITHUB_WORKSPACE"

      # --- NUOVO STEP DI DEBUG ---
      - name: 4. Verify Filesystem and Permissions
        run: |
          echo "--- Current Directory Content (Recursive Listing) ---"
          ls -laR
        working-directory: ${{ github.workspace }}

      - name: 5. Build the package
        run: sudo -u builder makepkg -s --noconfirm
        working-directory: ${{ github.workspace }}
        
      - name: 6. Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-package
          path: ./*.pkg.tar.zst
        working-directory: ${{ github.workspace }}
