name: Build Arch Linux Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-package:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Prepare Build Environment and Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git pnpm

      - name: Create Build User and Set Permissions
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          # Diamo la proprietà dell'intera cartella del progetto al builder
          chown -R builder:builder "$GITHUB_WORKSPACE"

      - name: Build The Package as Non-Root User
        # Eseguiamo makepkg nella cartella che contiene il PKGBUILD
        run: sudo -u builder makepkg -s --noconfirm
        # NOTA: Modifica questo percorso se il tuo PKGBUILD si trova altrove
        working-directory: ./packaging/arch
        
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-package
          path: "*.pkg.tar.zst"
        # L'artefatto si trova nella stessa cartella del build
        working-directory: ./packaging/arch
