name: Build Fedora Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-rpm-fedora:
    runs-on: ubuntu-latest
    
    container:
      image: fedora:42

    steps:
      # Step 1: Esegui un checkout COMPLETO del repository
      - name: 1. Check out repository code (full clone)
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0 dice all'azione di scaricare l'intera cronologia di Git,
          # rendendo disponibile la directory .git e abilitando comandi come 'git archive'.
          fetch-depth: 0

      # Step 2: Installa gli strumenti di base necessari subito
      - name: 2. Install Core Tools
        run: dnf install -y git tar gzip

      - name: 3. Download Bootloaders
        run: curl -LO https://github.com/pieroproietti/penguins-bootloaders/releases/download/v25.9.8/bootloaders.tar.gz

      - name: 4. Install Build Dependencies
        run: |
          # Installiamo solo le dipendenze di build, git è già installato
          dnf install -y rpm-build dnf-plugins-core
          dnf builddep -y ./packaging/rpm/penguins-eggs.spec

      - name: 5. Prepare RPM Sources
        run: |
          # Ora questo step funzionerà perché 'git' esiste ed è in un repo valido
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          mkdir -p $HOME/rpmbuild/SOURCES
          git archive --format=tar.gz --output=$HOME/rpmbuild/SOURCES/penguins-eggs-25.9.8.tar.gz HEAD
          cp bootloaders.tar.gz $HOME/rpmbuild/SOURCES/

      - name: 6. Build RPM package
        run: rpmbuild -ba ./packaging/rpm/penguins-eggs.spec

      - name: 7. Upload RPM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fedora-42-rpm
          path: ~/rpmbuild/RPMS/**/*.rpm