name: Build Openmamba Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-rpm-openmamba:
    runs-on: ubuntu-latest
    
    container:
      image: openmamba/openmamba

    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Install Core Tools
        run: dnf install -y git tar gzip curl rpm-build

      - name: 3. Install Build Dependencies Manually
        # --- QUESTA È LA SOLUZIONE FINALE ---
        # Abbandoniamo 'dnf builddep' perché ignora le nostre direttive.
        # Invece, estraiamo le dipendenze dal file .spec e forziamo
        # l'installazione della versione a 64-bit per ogni pacchetto.
        run: |
          grep '^BuildRequires:' ./packaging/rpm/penguins-eggs-openmamba.spec | \
            awk '{print $2}' | \
            sed 's/$/.x86_64/' | \
            xargs dnf install -y

      - name: 4. Build RPM package
        run: rpmbuild -ba ./packaging/rpm/penguins-eggs-openmamba.spec

      - name: 5. Upload RPM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openmamba-rolling-rpm
          path: ~/rpmbuild/RPMS/**/*.rpm

