name: Build Alpine Linux Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@vv4

      - name: Prepare Build Environment
        run: |
          apk update
          apk add alpine-sdk git nodejs npm sudo

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Create Build User and Keys
        run: |
          adduser -D builder
          addgroup builder abuild
          
          # Step 1: Come utente 'builder', GENERIAMO solo la chiave (senza -i)
          echo | sudo -u builder abuild-keygen -a
          
          # Step 2: Come 'root' (utente di default), COPIAMO la chiave pubblica
          cp /home/builder/.abuild/*.pub /etc/apk/keys/
          
          # Step 3: Diamo la proprieta' dei file del progetto al builder
          chown -R builder:builder "$GITHUB_WORKSPACE"

      - name: Build The Package as Non-Root User
        run: sudo -u builder abuild -r
        working-directory: ./packaging/alpine
        
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: alpine-package
          path: /home/builder/packages/**/*.apk

